name: clan-plugin
version: '1.0-SNAPSHOT'
main: com.suraev.ClanRunner
api-version: '1.21.1'


commands:
  clan create:
    description: создать клан
    usage: /clan create <name>
  clan invite:
    description: пригласить в клан
    usage: /clan invite <никнейм>
  clan accept:
    description: принять приглашение
    usage: /clan accept
  clan cancel:
    description: отменить приглашение
    usage: /clan cancel
  clan kick:
    description: кикнуть из клана
    usage: /clan kick <никнейм>
  clan leave:
    description: покинуть клан
    usage: /clan leave

