name: clan-plugin
version: '1.0-SNAPSHOT'
main: com.suraev.ClanRunner
api-version: '1.21.1'


commands:
  clan:
    description: управление кланом
    usage: |
      /clan create <name> - создать клан
      /clan invite <name> - пригласить в клан
      /clan accept - принять приглашение
      /clan cancel - отменить приглашение
      /clan kick <name> - кикнуть из клана
      /clan leave - покинуть клан
      /clan remove - удалить клан, лидером которого вы являетесь
      /clan info - информация о клане
      /clan members - информация о участниках клана

permissions:
  clan.remove:
    description: разрешение на удаление клана
    default: op


