name: clan-plugin
version: '1.0-SNAPSHOT'
main: com.suraev.ClanRunner
api-version: '1.21.1'


commands:
  clan:
permissions:
  clan.remove:
    description: разрешение на удаление клана
    default: op



